"""Configuration file for the Masterblog_api app."""

API_ERR_INVALID_POST_ID = "Invalid post ID"
API_ERR_INVALID_REQUEST_DATA = "Invalid request data"
API_ERR_TOO_MANY_REQUESTS = "Too many requests"
API_ERR_INTERNAL_SERVER_ERROR = "Internal server error"
API_ERR_404_NOT_FOUND = "404 Not found"

POST_FIELD_TITLE = "title"
POST_FIELD_CONTENT = "content"
POST_FIELD_AUTHOR = "author"
POST_FIELD_ID = "id"
POST_FILED_LIKEDBY = "liked_by"


API_DELETE_SUCCESS = "Post with id {id} has been deleted successfully."
API_ERR_METHOD_NOT_ALLOWED = "Method not allowed"
API_ERR_SEARCH_QUERY_PARAM_REQUIRED = "Query parameter is required"

API_SORT_PARAM = "sort"
API_SORT_DIRECTION_PARAM = "direction"
API_SORT_PARAM_ASC = "asc"
API_SORT_PARAM_DESC = "desc"
API_SORT_SORTABLE_FIELDS = [
    POST_FIELD_ID,
    POST_FIELD_TITLE,
    POST_FIELD_CONTENT,
]

API_SORT_VALID_DIRECTION = [API_SORT_PARAM_ASC, API_SORT_PARAM_DESC]

API_PAGINATION_DEFAULT_PAGE_SIZE = 10
API_PAGINATION_PARAM_PAGE = "page"
API_PAGINATION_PARAM_PERPAGE = "per_page"
API_PAGINATION_MAX_PAGE_SIZE = 100

API_SEARCH_QUERYABLE_FIELDS = [
    POST_FIELD_TITLE,
    POST_FIELD_CONTENT,
    POST_FIELD_AUTHOR,
]
API_SEARCH_PARAM_MATCHEITHER = "match_either"
API_SEARCH_PARAM_MATCHEITHER_VALIDS = {"true": True, "false": False}

LIST_PARAMS = [
    API_SORT_PARAM,
    API_SORT_DIRECTION_PARAM,
    API_PAGINATION_PARAM_PAGE,
    API_PAGINATION_PARAM_PERPAGE,
]
SEARCH_PARAMS = [
    *LIST_PARAMS,
    *API_SEARCH_QUERYABLE_FIELDS,
    API_SEARCH_PARAM_MATCHEITHER,
]

# parameters with a fixed set of allowed values
VALID_VALUES = {
    API_SORT_PARAM: API_SORT_SORTABLE_FIELDS,
    API_SORT_DIRECTION_PARAM: API_SORT_VALID_DIRECTION,
    API_SEARCH_PARAM_MATCHEITHER: API_SEARCH_PARAM_MATCHEITHER_VALIDS,
}
